name: Deploy

on:
  push:
    branches:
      - homework6

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Copy code to server
      run: |
        ssh-keyscan -H 87.251.73.21 >> ~/.ssh/known_hosts
        rsync -avz --exclude '.git*' ./ root@87.251.73.21:~/backend/

    - name: Deploy with Docker Compose
      run: |
        ssh root@87.251.73.21 "cd ~/backend && docker compose pull && docker compose up -d --build"

